# Generated by Django 4.2.3 on 2023-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Ecom/Pimg')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
