# Generated by Django 4.2.3 on 2023-08-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subCategory',
        ),
    ]
