# Generated by Django 4.2.3 on 2023-08-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
